deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  if: startsWith(github.ref, 'refs/tags/')

  steps:
    - uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig from secret
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Create Kubernetes Namespace
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        NAMESPACE=product-service-v${VERSION//./-}
        kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        kubectl apply -f k8s/deployment-v${VERSION//./-}.yml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/hpa.yaml
      env:
        KUBECONFIG: $HOME/.kube/config
